# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:future
twitter_username:future
github_username:future
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: weilai

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7e521510fffc332ad8ae                           #生成的clientID
  clientSecret: 21cb84e10e0d2139e5db8d72d9a0e6f4fbdd74a0   #生成的clientSecret
  repo: future2.github.io    #仓库名称
  owner: weilai   #github用户名
  admin:weilai
  distractionFreeMode: true #是否启用类似FB的阴影遮罩



# API settings
google_api_key:

# Build settings
markdown: kramdown
